package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/PuerkitoBio/goquery"
	"github.com/levigross/grequests"
)

const (
	problems    = "possible-problems"
	suggestions = "suggestions"
	lf          = "layout--formatting"
)

const rulesURl = "https://eslint.org/docs/latest/rules/"

func main() {
	rs, err := getRules()
	if err != nil {
		panic(err)
	}

	buildFile(rs)
}

func getRules() (map[string][]string, error) {
	resp, err := grequests.Get(rulesURl, nil)
	if err != nil {
		return nil, err
	}

	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(resp.Bytes()))
	if err != nil {
		return nil, err
	}

	rules := map[string][]string{
		problems:    {},
		suggestions: {},
		lf:          {},
	}

	currentRule := ""
	doc.Find("h2, a").Each(func(i int, s *goquery.Selection) {
		switch {
		case s.Is("h2"):
			v, ok := s.Attr("id")
			if ok {
				if _, ok := rules[v]; ok {
					currentRule = v
				}
			}

		case s.Is("a"):
			if currentRule == "" {
				return
			}
			c, ok := s.Attr("class")
			if ok && c == "rule__name" {
				r := s.Nodes[0].LastChild.Data
				rules[currentRule] = append(rules[currentRule], r)
			}
		}
	})
	return rules, nil
}

func buildFile(ruleMap map[string][]string) {
	fileName := "generated_rules.go"

	sortedRuleTypes := []string{lf, problems, suggestions}

	b := strings.Builder{}
	b.WriteString("// Code generated by generator/genrules. DO NOT EDIT.\n")
	b.WriteString("package plugin\n")
	b.WriteString("import \"github.com/cocov-ci/go-plugin-kit/cocov\"\n")
	b.WriteString("var rules = map[string]cocov.IssueKind{\n")

	ruleExists := map[string]bool{}

	for _, rType := range sortedRuleTypes {
		issueKind := ""
		switch rType {
		case suggestions:
			issueKind = "cocov.IssueKindConvention"
		case problems:
			issueKind = "cocov.IssueKindBug"
		case lf:
			issueKind = "cocov.IssueKindStyle"
		}

		rules := ruleMap[rType]
		sort.Strings(rules)
		for _, rule := range rules {
			if ok := ruleExists[rule]; ok {
				continue
			}
			b.WriteString(fmt.Sprintf("\"%s\": %s,\n", rule, issueKind))
		}
	}

	b.WriteString("}")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}

	if err = os.WriteFile(fileName, src, os.ModePerm); err != nil {
		panic(err)
	}
}
